version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQAGITTESTPPPrivate1811Project
  gitServerName: kusiTestprod477772
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
- name: WmSalesforceRESTProvider
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
